name: Manual Enrichment

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      
      # Package the jar file
      - name: package
        run: |
          mvn package -DskipTests
          echo Maven package success

      #Upload
      - uses: actions/upload-artifact@v3
        with:
          name: ProVerBMate
          path: target/ProVerBMate-1.4.0.jar

  enrich:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download
      - uses: actions/download-artifact@v3
        with:
          name: ProVerBMate

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Poll the ProverB
      - name: Curl Dataset
        run: |
          curl -LJO https://github.com/LiuLiujie/ProVerBMate-P2RConverter/releases/download/manual/ProVerB_1.4.0.owl
          echo Curl Dataset success

      # Convert
      - name: Enrichment
        run: |
          chmod 0755 ProVerBMate-1.4.0.jar
          java -jar ProVerBMate-1.4.0.jar --spring.profiles.active=daily --github-token=${{secrets.GIT_API}} --springer-key=${{secrets.SPRINGER_KEY}} --cross-ref.mailto=${{secrets.CROSS_REF}}
          echo Enrichment success.

      # Release
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "manual"
          prerelease: false
          title: "${{ steps.date.outputs.date }}"
          files: |
            enriched_ProVerB_1.4.0.owl
            *.jar
